<?php
/**
 * Copyright (c) 2013, Praxigento
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *  - Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 *      disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *      following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
?>
<?php
/**
 * Customer login form - auto redirect to account controller with custom LoginAs action.
 *
 * @see Nmmlm_Core_Block_Default
 */
?>
<?php
/** @var $this Mage_Adminhtml_Block_Template */
/** @var $authPack Praxigento_LoginAs_Model_Package */
$authPack = Mage::getSingleton('prxgt_lgas_model/package');
?>
<html>
<body>
<form action="<?php echo $authPack->getRedirectUrl() ?>"
      method="post" id="login-form">
    <?php /** Post file name with login parameters */?>
    <input type="hidden" name="<?php echo Praxigento_LoginAs_Config::REQ_PARAM_LAS_ID ?>"
           id="<?php echo Praxigento_LoginAs_Config::REQ_PARAM_LAS_ID ?>"
           value="<?php echo $authPack->getPackageId() ?>"/>
</form>
<script type="text/javascript">
    //<![CDATA[
    document.getElementById("login-form").submit();
    //]]>
</script>
</body>
</html>