<script>
	var SFdefault_language = '<?=$this->getLangDef() ?>';
</script>
<script src="<?php echo $this->getSkinUrl('forum/js/tiny_mce/tiny_mce.js') ?>"></script>
<!-- script src="<?php echo $this->getSkinUrl('forum/js/init_rte.js') ?>"></script !-->
<script>
initRTE = function(){


tinyMCE.init({
	mode : "textareas",

	theme : "advanced",

	language: (SFdefault_language ? SFdefault_language : 'en'),

	plugins : "<?php if(Mage::getStoreConfig('forum/tinymcesettings/use_image_resize')): ?>advimagescale,<?php endif; ?>autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave<?php if(Mage::getStoreConfig('forum/tinymcesettings/allow_backend')): ?>,simpleupload<?php endif; ?>",

	convert_urls : "false",
	theme_advanced_buttons1 : "bold,italic,underline,separator,formatselect,separator,forecolor,backcolor,separator,bullist,numlist,separator,outdent,indent,separator,undo,redo,separator,hr,removeformat,visualaid,image,simpleupload,media,link",

	theme_advanced_toolbar_location : "top",

    <?php if(Mage::getStoreConfig('forum/tinymcesettings/use_image_resize')): ?>
		advimagescale_max_width:  <?php echo (Mage::getStoreConfig('forum/tinymcesettings/maximum_image_width')?Mage::getStoreConfig('forum/tinymcesettings/maximum_image_width'): '400') ?>,
		advimagescale_maintain_aspect_ratio: true,
	    advimagescale_fix_border_glitch: true,
	    advimagescale_max_height: 1000,
	    advimagescale_noresize_all: true,
	    advimagescale_reject_external_dragdrop: true,
	 <?php endif; ?>
		theme_advanced_buttons2 : " separator,sub,sup,separator, charmap,emotions,removeformat",
		theme_advanced_buttons3 : "",

	<?php if(Mage::getStoreConfig('forum/tinymcesettings/allow_backend') && Mage::getStoreConfig('forum/tinymcesettings/connector_path') && Mage::getStoreConfig('forum/tinymcesettings/image_path')): ?>
		simpleupload_connector_path: '<?php echo Mage::getStoreConfig('forum/tinymcesettings/connector_path'); ?>',
		simpleupload_images_path: '<?php echo Mage::getStoreConfig('forum/tinymcesettings/image_path'); ?>',
	<?php endif; ?>

	inline_styles : true,
	force_br_newlines : "true",
	relative_urls: false,
	height:400,

	skin : "o2k7",
	skin_variant : "silver",


	// Drop lists for link/image/media/template dialogs
	template_external_list_url : "js/template_list.js",
	external_link_list_url : "js/link_list.js",
	external_image_list_url : "js/image_list.js",
	media_external_list_url : "js/media_list.js",
	autosave_ask_before_unload : false // Disable for example purposes
});

}

</script>
<script>
	Simple_Forum_INIT = setInterval(
		function(){
			if(typeof tinyMCE != 'undefined' && $('anchor-content')){
				initRTE();
				clearInterval(Simple_Forum_INIT);
			}
		}
	,500)
</script>
