<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
<div class="product-info-box">
    <div class="product-essential">
    	<div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shop">
		<?php if($this->getDisplayRSS()): ?>
			<div class="simple-forum-rss-link">
				<table align="right">
					<tr>
						<td valign="top" style="padding-top:5px">
							<a href="<?php echo $this->getRSSUrl() ?>">
								<img src="<?php echo $this->getSkinUrl('') ?>forum/images/rss.png" border="0"/>
							</a>
						</td>
						<td valign="top" style="padding:3px">
							<a class="simple-forum-rss-link-a" href="<?php echo $this->getRSSUrl() ?>">
								RSS
							</a>
						</td>
					</tr>
				</table>
			</div>
		<?php endif; ?>
        	<h3><?php echo $this->getForumTitle() ?></h3>
	
            <h4>
                <?php echo $this->__('Product') ?>: <a href="<?php echo $this->getProductBackLink() ?>"><?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?></a>
            </h4>
            <div class="divider"></div>
            
            <?php if ($_product->getShortDescription()):?>
                <h4><?php echo $this->__('Quick Overview') ?></h4>
                <div class="short-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
            <?php endif;?>
		</div>
	</div>
	
</div>
</div>