<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Kbase
 * @version    1.3.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php

$element = $this->getElement();

?>
<tr id="<?php echo $element->getHtmlId() ?>_container">
    <td class="label"><label for="<?php echo $element->getHtmlId() ?>_uploader"><?php echo $element->getLabel() ?></label></td>
    <td colspan="2" class="value" style="white-space:nowrap;width:auto;">
        <input type="file" value="" name="<?php echo $element->getName() ?>" id="<?php echo $element->getHtmlId() ?>_uploader" class="<?php echo $element->getClass() ?>" />
        <?php if($element->getValue()): ?>
            <br />
            <span class="<?php echo $element->getClass() ?>">
                <a href="<?php echo $this->getUrl('*/*/downloadAttachment', array('id' => $this->getRequest()->getParam('id'))) ?>" title="<?php echo $this->__('Download') ?>"><?php echo htmlspecialchars($element->getValue()) ?></a>
            </span>
            <input type="checkbox" name="<?php echo $element->getName() ?>_delete" id="<?php echo $element->getHtmlId() ?>_delete" class="delete" />
            <label for="<?php echo $element->getHtmlId() ?>_delete"><?php echo $this->__('Delete file') ?></label>
            <input type="hidden" id="<?php echo $element->getHtmlId() ?>_old" name="<?php echo $element->getName() ?>_old" value="<?php echo $element->getValue() ?>" />
        <?php endif; ?>
    </td>
</tr>