<?php
/**
 * webideaonline.com.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://webideaonline.com/licensing/
 *
 */
?>
<?php $forums = $this->getForums(); ?>
<?php $total  = $this->getTotalForums() ?>
<?php if($forums->getSize()): ?>
<div class="block our-forums box base-mini">
    <div class="block-title head">
        <strong><span><?php echo $this->_getTitle(); ?></span></strong>
    </div>
    <div class="block-content content">
          <ul class="our-forums">
          	   <?php $all = 0; ?>
               <?php foreach($forums as $forum): ?>
               		<?php $all++; ?>
               		<li <?php if($all == $total): ?>class="last" <?php endif; ?>><a href="<?php echo $this->_getLink( $forum ) ?>"><?php echo $forum->getTitle() ?> </a></li>
				<?php endforeach; ?>
          </ul>
    </div>
</div>

<?php endif; ?>