<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-catalogsale-products">
    <div class="block block-specials">
        <div class="block-title">
            <strong><span><?php echo $this->__('Sale Products') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-list-sale" id="widget-catalogsale-products-<?php echo $suffix; ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(88, 88) ?>" width="88" height="88" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                        <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" class="link_view"><?php echo $this->__('View') ?></a>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </div>
</div>
<?php endif; ?>
