<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div class="product-view product-view-fancybox">
  <div class="messege-product">Please specify the product's required option(s).</div>
  <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
      <div class="no-display">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
      </div>
      <div class="product-shop">
 		<div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
	        <div class="fancy-right">
	          <div class="product-name">
	            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
	          </div>
	            <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
	          <div class="share bordercolor">
	            <!-- AddThis Button BEGIN -->
	            <div class="addthis_toolbox addthis_default_style "> <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a> <a class="addthis_button_tweet"></a> <a class="addthis_button_google_plusone" g:plusone:size="medium"></a> <a class="addthis_counter addthis_pill_style"></a> </div>
	            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f419f410efe76d3"></script>
	          </div>
              <div class="clear"></div>
	        <?php echo $this->getChildHtml('product_type_data') ?>
            <div class="clear"></div>
	        <?php if (!$this->hasOptions()):?>
	        <div class="add-to-box">
	          <?php if($_product->isSaleable()): ?>
	          <?php echo $this->getChildHtml('addtocart') ?>
	          <?php endif; ?>
	        </div>
	        <?php endif; ?>
	        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
	        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
	        <?php endif;?>
	        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
	        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
	        <?php endif;?>
	        <div class="clearer"></div>
        </div>
        </div>
        <div class="clear"></div>
      <!--      <div class="video">


	<p><span>Video review of:</span> Lorem ipsum dolor sit amet conse ctetur adipisicing elit</p>

<iframe width="630" height="300" src="http://www.youtube.com/embed/t4H_Zoh7G5A" frameborder="0" allowfullscreen></iframe>
        </div>-->
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
    	productAddToCartForm.submit = function(button, url) {
		if (this.validator.validate()) {
			var form = this.form;
			var oldUrl = form.action;
			if (url) {
				form.action = url;
			}
			var e = null;
			// Start of our new ajax code
			if (!url) {
				url = jQuery('#product_addtocart_form').attr('action');
			}
			url = url.replace("checkout/cart","ajax/index"); // New Code
			var data = jQuery('#product_addtocart_form').serialize();
			data += '&isAjax=1';
			jQuery('#ajax_loader').show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					type : 'post',
					data : data,
					success : function(data) {
						jQuery('#ajax_loader').hide();
						parent.setAjaxData(data,true);
                        
						jQuery('body').append('<div class="alert"></div>');
						jQuery('.alert').slideDown(400);
						jQuery('.alert').html(data.message).append('<button></button>');
				jQuery('button').click(function () {
                jQuery('.alert').slideUp(400); });	
					jQuery('.alert').slideDown('400',function(){
						setTimeout(function(){
							jQuery('.alert').slideUp('400',function(){jQuery(this).slideUp(400)});},7000)
						});
	
					}
				});
			} catch (e) {
			}
			// End of our new ajax code
			this.form.action = oldUrl;
			
			if (e) {
				throw e;
			}
		}
	}.bind(productAddToCartForm);
    productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    <script>
	jQuery(document).ready(function(){
	  if(jQuery(".product-options").is(":visible")){
	  jQuery(".product-view").parent().find(".messege-product").addClass('none-messege'); }
	  jQuery('button').click(function () {
	  jQuery('.messege-product').slideUp(400);});	
	  jQuery('.messege-product').find(function(){
		 setTimeout(function(){	
			jQuery('.messege-product').slideUp('400',function(){
				jQuery(this).slideUp(400)});},7000)
		 });
	});
	jQuery('.messege-product').append('<button></button>');
</script>
  </div>
</div>
