<div class="forum-statistic-block" >
<h4><?php echo $this->__('Statistic') ?></h4>
<div class="forum-hor-divider">&nbsp;</div>
	<div>
	<?php echo $this->__('Total Forums') ?>: <b><?php echo $this->getTotalForums() ?></b>.&nbsp; 
	<?php echo $this->__('Total Topics') ?>: <b><?php echo $this->getTotalTopics() ?></b>.&nbsp; 
	<?php echo $this->__('Total Posts') ?>: <b><?php echo $this->getTotalPosts() ?></b>.&nbsp; 
	<?php echo $this->__('Total Active Members') ?>: <b><?php echo $this->getTotalActiveCustomers() ?></b>.&nbsp; 
</div>
</div>