<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    3.0.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>

<script type="text/javascript">
//<![CDATA[
    var AWACP_CONFIG = {
        mageVersion: '<?php echo Mage::getVersion();?>',
        useProgress : <?php echo intval(Mage::getStoreConfig('ajaxcartpro/general/showprogressanimation')) ?>,
        addProductConfirmationEnabled : <?php echo intval(Mage::getStoreConfig('ajaxcartpro/addproductconfirmation/enabled')) ?>,
        removeProductConfirmationEnabled : <?php echo intval(Mage::getStoreConfig('ajaxcartpro/removeproductconfirmation/enabled')) ?>,
        dialogsVAlign: '<?php echo Mage::getStoreConfig('ajaxcartpro/general/progressanimation') ?>',
        cartAnimation: '<?php echo Mage::getStoreConfig('ajaxcartpro/general/cartanimation') ?>',
        hasFileOption : <?php echo Mage::helper('ajaxcartpro')->hasFileOption() ? 'true' : 'false' ?>,
        addProductCounterBeginFrom : <?php echo intval(Mage::getStoreConfig('ajaxcartpro/addproductconfirmation/countdown')) ?>,
        removeProductCounterBeginFrom : <?php echo intval(Mage::getStoreConfig('ajaxcartpro/removeproductconfirmation/countdown')) ?>
    }

    Event.observe(document, 'dom:loaded', function(){
        AW_AjaxCartPro.init(AWACP_CONFIG);
    });

//]]>
</script>
