<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    3.0.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<div>
    <?php $_product = $this->getProduct() ?>
    <script type="text/javascript">
        optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
        optionsPrice.productType = '<?php echo $_product->getTypeId() ?>';
        if (typeof(Enterprise) != 'undefined' && typeof(Enterprise.Bundle) != 'undefined') {
            (function(){
                var oldFn = Enterprise.Bundle.swapReloadPrice;
                Enterprise.Bundle.swapReloadPrice = function() {
                    if (Enterprise.Bundle.isSwaped === true) {
                        return;
                    }
                    oldFn();
                    Enterprise.Bundle.isSwaped = true;
                }
            })();
        }
    </script>
    <form action="<?php echo Mage::helper('ajaxcartpro/catalog')->getSubmitUrl($this, $_product) ?>" method="post"
          id="product-addtocart-form-acp"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" value="<?php echo $_product->getId() ?>" name="product">
        <input type="hidden" value="1" name="awacp-options-form" />
        <div id="bundle-product-wrapper">
            <div id="acp-product-options">
                <div class="product-options" id="product-options-wrapper" style="margin:0">
                    <ul class="acp-msg-block error-msg ajaxcartpro-box-hide"></ul>
                    <div class="product-name"><?php echo $_product->getName() ?></div>
                    <div id="acp-product-type-data" class="ajaxcartpro-box-hide">
                        <?php echo $this->getChildHtml('product_type_data') ?>
                    </div>
                    <?php echo str_replace('var ', '', $this->getChildHtml('product_options'));?>
                    <?php echo $this->getChildHtml('product_configurable_options');?>
                    <?php echo $this->getChildHtml('product_downloadable_options');?>
                    <?php echo $this->getChildHtml('product_bundle_options');?>
                    <?php echo $this->getChildHtml('product_price');?>
                    <?php if(!$_product->isGrouped()): ?>
                        <label for="qty"><?php echo $this->__('Qty:') ?></label>
                        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                    <?php endif; ?>
                    <div class="aw-acp-btn-container">
                        <a href="#" class="aw-acp-continue"><?php echo $this->__('Cancel')?></a>
                        <a href="#" class="aw-acp-checkout" class="focus"><?php echo $this->__('Add to cart')?></a>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            if (typeof(Enterprise) != 'undefined' && typeof(Enterprise.Bundle) != 'undefined') {
                $H(optionsPrice.containers).each(function(pair){
                    if (!$(pair.value) && $(pair.value + optionsPrice.duplicateIdSuffix)) {
                        $(pair.value + optionsPrice.duplicateIdSuffix).setAttribute('id', pair.value);
                    }
                });
            }
        </script>
    </form>
    <script type="text/javascript">
        decorateGeneric($$('#product-options-wrapper dl'), ['last']);
        var productAddToCartFormAcp = new VarienForm('product-addtocart-form-acp');
        var validateDownloadableCallback = function (elmId, result)
        {
            var container = $('downloadable-links-list');
            if (result == 'failed') {
                container.removeClassName('validation-passed');
                container.addClassName('validation-failed');
            } else {
                container.removeClassName('validation-failed');
                container.addClassName('validation-passed');
            }
        }

        var validateOptionsCallback = function(elmId, result)
        {
            var container = $(elmId).up('ul.options-list');
            if (result == 'failed') {
                container.removeClassName('validation-passed');
                container.addClassName('validation-failed');
            } else {
                container.removeClassName('validation-failed');
                container.addClassName('validation-passed');
            }
        }

    </script>
</div>
